pipeline { 
  agent any

environment { ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg" }

stages { 
  stage("Initial cleanup") { 
    steps { 
      dir("${WORKSPACE}") { 
        deleteDir() 
        } 
    } 
  }
}
stage('Checkout SCM') {
  steps {
    git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Uzuazoraro/AnsibleConfMgt.git'
  }
}

stage('Prepare Ansible For Execution') {
  steps {
    sh 'echo ${WORKSPACE}'
    sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
  }
}

stage('Run Ansible Playbook') {
  steps {
    ansiblePlaybook become: true, colorized: true, credentialsId: '62b9ff22-34f7-46cc-9e39-e7a167788af4', disableHostKeyChecking: true, installation: 'ansible2', inventory: 'dev.yml', playbook: 'site.yml', vaultTmpPath: ''
  }
}

stage('Clean Workspace after build') {
  steps {
    cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
  }
}
}